# Generated by Django 3.0.3 on 2021-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradus', models.FloatField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
                ('longtitude', models.FloatField(max_length=100)),
            ],
        ),
    ]
