# Generated by Django 3.0.3 on 2021-11-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infotrafficlight',
            options={'verbose_name': 'Светофор', 'verbose_name_plural': 'Список светофоров'},
        ),
        migrations.AddField(
            model_name='infotrafficlight',
            name='photo',
            field=models.FileField(default=1987, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infotrafficlight',
            name='gradus',
            field=models.FloatField(max_length=100, verbose_name='Градусы'),
        ),
        migrations.AlterField(
            model_name='infotrafficlight',
            name='latitude',
            field=models.FloatField(max_length=100, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='infotrafficlight',
            name='longtitude',
            field=models.FloatField(max_length=100, verbose_name='Широта'),
        ),
    ]
