# Generated by Django 3.1.5 on 2022-03-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='photo',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
