# Generated by Django 3.1.5 on 2022-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220316_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
