# Generated by Django 3.1.5 on 2022-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220316_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotrafficlight',
            name='json',
            field=models.JSONField(blank=True, default=None, verbose_name='JSON'),
        ),
    ]
