# Generated by Django 3.1.5 on 2022-03-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_infotrafficlight_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotrafficlight',
            old_name='json',
            new_name='data',
        ),
    ]
