# Generated by Django 3.1.5 on 2022-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220318_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='data',
            field=models.JSONField(default=0, null=True, verbose_name='Код для коробки'),
        ),
    ]
