# Generated by Django 3.1.5 on 2022-03-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220318_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='data',
            field=models.JSONField(default={}, null=True, verbose_name='Код для коробки'),
        ),
    ]
