# Generated by Django 3.1.5 on 2022-03-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220318_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='data',
            field=models.JSONField(default='{}', null=True, verbose_name='Код для коробки'),
        ),
    ]
