# Generated by Django 3.1.5 on 2022-03-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220318_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotrafficlight',
            old_name='data',
            new_name='json',
        ),
    ]
