# Generated by Django 3.1.5 on 2022-04-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_traficlightname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.traficlightname', verbose_name='shelfafter'),
        ),
    ]
