# Generated by Django 3.1.5 on 2022-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220418_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotrafficlight',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Айди устройства'),
        ),
    ]
