# Generated by Django 3.1.5 on 2022-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_infotrafficlight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotrafficlight',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Айди устройства'),
        ),
    ]
