# Generated by Django 3.1.5 on 2022-06-17 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_auto_20220420_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(null=True, verbose_name='Айди устройства')),
                ('is_information_collector', models.BooleanField(null=True, verbose_name='Айди устройства')),
                ('is_handler', models.BooleanField(null=True, verbose_name='Айди устройства')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='shelfafter')),
            ],
        ),
    ]
