# Generated by Django 3.1.5 on 2022-06-17 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfAccelerometer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(default='0', max_length=100, verbose_name='x')),
                ('y', models.CharField(max_length=100, null=True, verbose_name='y')),
                ('z', models.CharField(max_length=100, null=True, verbose_name='z')),
            ],
        ),
        migrations.AlterField(
            model_name='userroles',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id пользователя'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='is_admin',
            field=models.BooleanField(null=True, verbose_name='Роль администратора'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='is_handler',
            field=models.BooleanField(null=True, verbose_name='Роль обработчика'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='is_information_collector',
            field=models.BooleanField(null=True, verbose_name='Роль сборщика информации'),
        ),
        migrations.RenameModel(
            old_name='InfoTrafficLight',
            new_name='TrafficLight',
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trafficlight', verbose_name='shelfafter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='shelfafter')),
            ],
        ),
    ]
