# Generated by Django 3.1.5 on 2022-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220617_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlight',
            name='json',
        ),
        migrations.AddField(
            model_name='traficlightname',
            name='gradus',
            field=models.FloatField(max_length=100, null=True, verbose_name='Градусы'),
        ),
        migrations.AddField(
            model_name='traficlightname',
            name='latitude',
            field=models.FloatField(max_length=100, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='traficlightname',
            name='longtitude',
            field=models.FloatField(max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='traficlightname',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Айди устройства'),
        ),
    ]
