# Generated by Django 3.1.5 on 2022-06-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220617_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateofaccelerometer',
            name='traffic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trafficlight', verbose_name='shelfafter'),
        ),
    ]
