# Generated by Django 3.1.5 on 2022-06-17 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_dateofaccelerometer_traffic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device',
            field=models.CharField(max_length=100, null=True, verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
